apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    app.kubernetes.io/name: app-config
data:
  connection_string: "Host=db.default.svc.cluster.local;Port=5432;Database=*database*;Username=*username*;Password=*password*"
  auth_token_issuer: "* JSON Web Token (JWT) Issuer Name *"
  auth_token_audience: "* JSON Web Token (JWT) Audience Name *"
  auth_token_expiration: "* JSON Web Token (JWT) Expiration Time (.NET TimeSpan Convention) *"
  reset_token_url: "* The URL to WebSite where email with reset password token links to *"
  reset_token_expiration: "* The Reset Password Token Expiration (Minimum 1 min, Maximum 1 day) *"
  rabbitmq_connection_string: "amqp://*login*:*password*@rabbit-mq.default.svc.cluster.local:5672"
  rabbitmq_queue_name: "* RabbitMQ Notification Queue Name *"
  cache_connection_string: "redis://*login*:*password*@redis.default.svc.cluster.local:6379"
  smtp_email_name: "* Name from which the email letter will be sent *"
  smtp_email_address: "* Email Address from which the email letter will be sent*"
  smtp_host: "* Host of SMTP Server *"
  smtp_port: "* Port of SMTP Server *"
  smtp_ssl: "* Is SSL Used? (true/false) *"

---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: app-secrets
  labels:
    app.kubernetes.io/name: app-secrets
stringData:
  auth_token_key: "* JSON Web Token (JWT) Secret Key (Minimum 384 bits) *"
  smtp_login: "* Login for SMTP Server *"
  smtp_password: "* Password for SMTP Server *"
