apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app.kubernetes.io/name: db-svc
    app.kubernetes.io/component: database
spec:
  selector:
    app.kubernetes.io/name: database
    app.kubernetes.io/component: database
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: db