apiVersion: v1
kind: Service
metadata:
  name: users
  labels:
    app.kubernetes.io/name: users-service
    app.kubernetes.io/component: users-api
spec:
  selector:
    app.kubernetes.io/name: users-pod
    app.kubernetes.io/component: users-api
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http