apiVersion: v1
kind: Service
metadata:
  name: notification
  labels:
    app.kubernetes.io/name: notification-svc
    app.kubernetes.io/component: notification-api
spec:
  selector:
    app.kubernetes.io/name: notification-pod
    app.kubernetes.io/component: notification-api
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http