apiVersion: v1
kind: Service
metadata:
  name: rabbit-mq
  labels:
    app.kubernetes.io/name: rabbitmq-svc
    app.kubernetes.io/component: message-broker
spec:
  selector:
    app.kubernetes.io/name: rabbitmq
    app.kubernetes.io/component: message-broker
  ports:
    - name: amqp
      port: 5672
      targetPort: amqp