apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-microservices
  labels:
    app.kubernetes.io/name: users
    app.kubernetes.io/component: users-api
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: users-pod
      app.kubernetes.io/component: users-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: users-pod
        app.kubernetes.io/component: users-api
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000

      initContainers:
        - name: wait-db
          image: postgres:16-alpine
          command: ['sh', '-c']
          args:
            - |
                while !pg_isready -h db-svc.default.svc.cluster.local -p 5432 -U postgres; do
                  echo "Database is not available now."
                  sleep 5
                done
                
        - name: wait-rabbit
          image: busybox
          command: ['sh', '-c']
          args:
            - |
                until nc -z rabbit-mq.default.svc.cluster.local 5672; do
                  echo "RabbitMQ is not available now."
                  sleep 5
                done
      containers:
        - name: users-msvc
          image: hikashi/msvc-users:issue89.v1
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 30
            failureThreshold: 3
            periodSeconds: 10
          
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"

            limits:
              memory: "512Mi"
              cpu: "500m"

          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db.host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db.port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: db.name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: db.user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: db.pass
            - name: CONNECTION_STRING
              value: "Host=$(DB_HOST);Port=$(DB_PORT);Database=$(DB_NAME);Username=$(DB_USER);Password=$(DB_PASS)"
            - name: AUTHORIZATION_TOKEN__ISSUER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: auth_token.issuer
            - name: AUTHORIZATION_TOKEN__AUDIENCE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: auth_token.audience
            - name: AUTHORIZATION_TOKEN__EXPIRATION
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: auth_token.expiration
            - name: AUTHORIZATION_TOKEN__KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: auth_token.key
            - name: RESET_TOKEN__URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: reset_token.url
            - name: RESET_TOKEN__EXPIRATION
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: reset_token.expiration
            - name: RABBIT_USER
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: rabbit.user
            - name: RABBIT_PASS
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: rabbit.pass
            - name: RABBIT_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: rabbit.host
            - name: RABBIT_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: rabbit.port
            - name: RABBIT_MQ__CONNECTION_STRING
              value: "amqp://$(RABBIT_USER):$(RABBIT_PASS)@$(RABBIT_HOST):$(RABBIT_PORT)"
            - name: RABBIT_MQ__QUEUE_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: rabbit.queue
            - name: CACHE_CONNECTION
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: cache.conn_string