apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  appsettings.Production.json: |
    {
      "ReverseProxy": {
        "Clusters": {
          "users-svc": {
            "Destinations": {
              "dest1": {
                "Address": "http://users.default.svc.cluster.local:8080"
              }
            }
          }
        }
      }
    }